[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-freefont", "font-noto-emoji"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[start]
cmd = "node index.js"
